# Define the experiment
# - each 'block' is a sub-element of an experiment. Blocks can be used to
#   structure an experiment
# - each 'section' is a sub-element of a block. Sections can be used to
#   structure blocks
#
# - 'attribute' must match attributes.yml
# - 'name' is optional an can be used to describe a section.
# - 'reference' and 'test' must match the stimuli.yml
#
# All information contained in this config can be used to save the results of
# the experiment
- block:
  - section:
      attribute: difference
      name: null
      reference: 1
      test:
        - 2
        - 3
  - section:
      attribute: difference
      name: null
      reference: 1
      test:
        - 2
        - 3
- block:
  - section:
      attribute: coloration_bright_dark
      name: null
      reference: 1
      test:
        - 2
        - 3
