# Define the experiment
# - each 'block' is a sub-element of an experiment. Blocks can be used to
#   structure an experiment
# - each 'section' is a sub-element of a block. Sections can be used to
#   structure blocks
#
# - 'block_name' and 'section_name' are optional an can be used to describe a
#   part of an experiment
# - 'attribute' must match attributes.yml
# - 'reference' and 'test' must match the stimuli.yml
#
# All information contained in this config can be used to save the results of
# the experiment
- block:
  - block_name: Block 1
  - section:
      section_name: Section 1
      attribute: difference
      reference: 1
      test: [2, 3]
  - section:
      section_name: Section 2
      attribute: difference
      reference: 1
      test: [2, 3]
- block:
  - block_name: Block 2
  - section:
      section_name: Section 3
      attribute: tone_color_bright-dark
      reference: 1
      test: [2, 3]
